export const UPGRADES = [
  {
    id: 'grupo_exclusivo',
    nome: 'Grupo Exclusivo Selva',
    emoji: '👥',
    preco: 9.90,
    precoFormatado: 'R$ 9,90',
    tag: 'MAIS POPULAR',
    tagColor: '#FF6B35',
    cor: '#0F1F0A',
    destaque: false,
    tipo: 'mensal',
    beneficios: [
      'Chat exclusivo com membros da comunidade Selva',
      'Compartilhe receitas e resultados',
      'Suporte mútuo entre praticantes',
      'Desafios semanais em grupo',
      'Conteúdo exclusivo dos membros',
    ],
    descricaoBreve: 'Faça parte da tribo. Comunidade exclusiva de praticantes.',
    descricaoCompleta: 'Junte-se a centenas de praticantes da Dieta da Selva. Compartilhe sua jornada, troque receitas, celebre conquistas e mantenha a motivação em alta com o suporte da comunidade.',
  },
  {
    id: 'ia_selva',
    nome: 'IA Selva Premium',
    emoji: '🤖',
    preco: 19.90,
    precoFormatado: 'R$ 19,90',
    tag: 'EXCLUSIVO',
    tagColor: '#7C3AED',
    cor: '#0D0D1A',
    destaque: true,
    tipo: 'mensal',
    beneficios: [
      'Acesso ilimitado à IA especializada em Dieta da Selva',
      'Respostas personalizadas para suas dúvidas',
      'Criação de cardápios personalizados',
      'Análise de refeições e sugestões',
      'Suporte 24h sem filas de espera',
    ],
    descricaoBreve: 'A IA especialista em Dieta da Selva no seu bolso.',
    descricaoCompleta: 'A IA Selva é treinada especificamente nos princípios da Dieta da Selva. Tire dúvidas sobre alimentos, peça cardápios personalizados, adapte receitas — tudo com respostas precisas e alinhadas ao método.',
  },
  {
    id: 'lista_compras',
    nome: 'Lista de Compras Econômica',
    emoji: '🛒',
    preco: 12.90,
    precoFormatado: 'R$ 12,90',
    tag: 'ECONÔMICO',
    tagColor: '#059669',
    cor: '#041A0F',
    destaque: false,
    tipo: 'unico',
    beneficios: [
      'Lista completa de 50+ itens por menos de R$ 180/semana',
      'Substitutos baratos para cada ingrediente premium',
      'Onde comprar mais barato (mercados vs feiras)',
      'Dicas de compra em atacado',
      'Atualizada mensalmente com preços de mercado',
    ],
    descricaoBreve: 'Faça a dieta gastando pouco. Lista completa e econômica.',
    descricaoCompleta: 'Você não precisa gastar muito para fazer a Dieta da Selva. Esta lista foi criada para quem quer resultados sem estourar o orçamento. Itens selecionados pelo menor custo-benefício nutritivo.',
  },
  {
    id: 'nutri_coach',
    nome: 'IA Nutri Coach',
    emoji: '🥗',
    preco: 37.00,
    precoFormatado: 'R$ 37,00',
    tag: 'AVANÇADO',
    tagColor: '#DC2626',
    cor: '#1A0505',
    destaque: true,
    tipo: 'mensal',
    beneficios: [
      'Coach nutricional IA com protocolo personalizado',
      'Análise do seu perfil físico e objetivos',
      'Plano de 30 dias adaptado ao seu corpo',
      'Monitoramento de progresso semanal',
      'Ajustes de cardápio baseados nos seus resultados',
      'Integração com os exercícios dos 21 dias',
    ],
    descricaoBreve: 'Seu nutricionista pessoal powered by IA.',
    descricaoCompleta: 'O Nutri Coach vai além de responder perguntas. Ele analisa seu perfil, objetivos e preferências para criar um protocolo nutricional 100% personalizado baseado nos princípios da Dieta da Selva.',
  },
  {
    id: 'vitalicio',
    nome: 'Acesso Vitalício',
    emoji: '♾️',
    preco: 29.90,
    precoFormatado: 'R$ 29,90',
    tag: 'MELHOR CUSTO',
    tagColor: '#D97706',
    cor: '#140E00',
    destaque: false,
    tipo: 'vitalicio',
    beneficios: [
      'Acesso vitalício a todas as receitas do app',
      'Atualizações semanais com novas receitas',
      'Novos planos de exercícios todo mês',
      'Acesso antecipado a novidades',
      'Sem mensalidade — pague uma vez, use sempre',
    ],
    descricaoBreve: 'Pague uma vez. Use para sempre. Atualizações toda semana.',
    descricaoCompleta: 'Investimento único com retorno vitalício. Todo conteúdo do app + todas as atualizações semanais de receitas, exercícios e dicas. Nunca mais pague mensalidade.',
  },
  {
    id: 'premium_total',
    nome: 'Premium Total Vitalício',
    emoji: '👑',
    preco: 97.00,
    precoFormatado: 'R$ 97,00',
    tag: 'TUDO INCLUSO',
    tagColor: '#F59E0B',
    cor: '#0A0A08',
    destaque: true,
    tipo: 'vitalicio',
    melhorValor: true,
    incluiTodos: true,
    beneficios: [
      '✅ TUDO do Acesso Vitalício',
      '✅ Grupo Exclusivo Selva',
      '✅ IA Selva Premium ilimitada',
      '✅ Lista de Compras Econômica',
      '✅ IA Nutri Coach da Selva',
      'Atualizações DIÁRIAS de conteúdo',
      'Acesso beta a funcionalidades futuras',
      'Badge exclusivo de membro Fundador',
      'Suporte prioritário',
    ],
    descricaoBreve: 'O pacote completo. Todos os upgrades + atualizações diárias.',
    descricaoCompleta: 'O pacote definitivo da Dieta da Selva. Inclui absolutamente tudo: todos os upgrades, atualizações diárias de conteúdo, acesso antecipado a features e o status de membro Fundador. Uma vez. Para sempre.',
  },
];

export const LISTA_COMPRAS = {
  totalEstimado: 'R$ 175,00',
  categorias: [
    {
      nome: '🥩 PROTEÍNAS',
      cor: '#DC2626',
      itens: [
        { item: 'Carne moída (acém)', quantidade: '1kg', preco: 'R$ 22,00', dica: 'Compre em atacado — até 30% mais barato' },
        { item: 'Ovos caipira (dúzia)', quantidade: '2 dúzias', preco: 'R$ 18,00', dica: 'Ovos comuns são igualmente nutritivos' },
        { item: 'Frango inteiro', quantidade: '1,5kg', preco: 'R$ 16,00', dica: 'Frango inteiro é mais barato por quilo' },
        { item: 'Sardinha em conserva', quantidade: '4 latas', preco: 'R$ 16,00', dica: 'Rica em ômega-3 — fonte de proteína barata' },
        { item: 'Fígado bovino', quantidade: '500g', preco: 'R$ 12,00', dica: 'O alimento mais nutritivo e mais barato' },
        { item: 'Costela bovina (ripa)', quantidade: '1kg', preco: 'R$ 28,00', dica: 'Cozinhe lentamente para amaciar' },
      ],
    },
    {
      nome: '🧈 GORDURAS BOAS',
      cor: '#D97706',
      itens: [
        { item: 'Manteiga sem sal', quantidade: '200g', preco: 'R$ 9,00', dica: 'Prefira manteiga de verdade à margarina' },
        { item: 'Azeite de oliva', quantidade: '500ml', preco: 'R$ 18,00', dica: 'Marca própria economiza até 40%' },
        { item: 'Óleo de coco', quantidade: '200ml', preco: 'R$ 14,00', dica: 'Use em pequenas quantidades — dura semanas' },
        { item: 'Bacon em pedaço', quantidade: '300g', preco: 'R$ 14,00', dica: 'Bacon em peça é mais barato e saboroso' },
      ],
    },
    {
      nome: '🥛 LATICÍNIOS',
      cor: '#7C3AED',
      itens: [
        { item: 'Leite integral (caixinha)', quantidade: '2 litros', preco: 'R$ 10,00', dica: 'Integral tem mais gordura boa que o desnatado' },
        { item: 'Iogurte natural integral', quantidade: '2 potes 400g', preco: 'R$ 12,00', dica: 'Sem adição de açúcar ou aromas artificiais' },
        { item: 'Queijo muçarela', quantidade: '400g', preco: 'R$ 16,00', dica: 'Compre em blocos — mais barato que fatiado' },
        { item: 'Queijo coalho', quantidade: '300g', preco: 'R$ 10,00', dica: 'Ótimo para grelhar — não derrete' },
      ],
    },
    {
      nome: '🍠 TUBÉRCULOS',
      cor: '#059669',
      itens: [
        { item: 'Batata inglesa', quantidade: '2kg', preco: 'R$ 8,00', dica: 'Uma das fontes de carboidratos mais baratas' },
        { item: 'Mandioca/macaxeira', quantidade: '1kg', preco: 'R$ 5,00', dica: 'Compre descascada e embalada — mais prática' },
        { item: 'Arroz branco', quantidade: '2kg', preco: 'R$ 7,00', dica: 'Arroz branco simples — sem necessidade de integral' },
        { item: 'Batata-doce', quantidade: '1kg', preco: 'R$ 7,00', dica: 'Rica em fibras e minerais' },
      ],
    },
    {
      nome: '🍎 FRUTAS',
      cor: '#EC4899',
      itens: [
        { item: 'Banana (penca)', quantidade: '~8 bananas', preco: 'R$ 5,00', dica: 'A fruta mais barata — ótima pós-treino' },
        { item: 'Mamão formosa', quantidade: '1 unidade', preco: 'R$ 6,00', dica: 'Compre verde e deixe amadurecer em casa' },
        { item: 'Laranja (saco)', quantidade: '2kg', preco: 'R$ 8,00', dica: 'Consumir inteira — não em suco' },
        { item: 'Maçã fuji', quantidade: '~4 unidades', preco: 'R$ 9,00', dica: 'Comer com casca para mais fibras' },
      ],
    },
    {
      nome: '🥬 SALADAS',
      cor: '#16A34A',
      itens: [
        { item: 'Alface crespa (pé)', quantidade: '2 pés', preco: 'R$ 4,00', dica: 'Cultivar em vaso em casa economiza ainda mais' },
        { item: 'Tomate (kg)', quantidade: '1kg', preco: 'R$ 6,00', dica: 'Em promoção, pode congelar' },
        { item: 'Pepino', quantidade: '2 unidades', preco: 'R$ 4,00', dica: 'Hidratante e perfeito para saladas' },
        { item: 'Rúcula (maço)', quantidade: '1 maço', preco: 'R$ 3,00', dica: 'Muito barata nas feiras livres' },
      ],
    },
    {
      nome: '🧂 TEMPEROS',
      cor: '#6B7280',
      itens: [
        { item: 'Sal grosso marinho', quantidade: '500g', preco: 'R$ 3,00', dica: 'Não refinado tem mais minerais' },
        { item: 'Pimenta-do-reino', quantidade: '50g', preco: 'R$ 4,00', dica: 'Em grão e moa na hora — mais sabor' },
        { item: 'Alho (cabeça)', quantidade: '1 cabeça', preco: 'R$ 3,00', dica: 'Natural é mais barato que o picado' },
        { item: 'Limão', quantidade: '6 unidades', preco: 'R$ 4,00', dica: 'Essencial para temperar carnes e saladas' },
        { item: 'Mel puro', quantidade: '300g', preco: 'R$ 18,00', dica: 'Use com moderação' },
      ],
    },
  ],
  dicas: [
    '🏪 Compre carnes na feira ou açougue de bairro — até 40% mais barato que supermercado',
    '📦 Compre ovos, frango e carne em maior quantidade e congele',
    '🕐 Vá às feiras no final do dia — frutas e verduras são vendidas mais baratas',
    '🔄 Varie os cortes — acém, músculo e coxão duro são baratos e nutritivos',
    '💧 Faça caldo de ossos com ossos descartados — grátis e muito nutritivo',
    '🌿 Horta caseira de rúcula e cebolinha economiza R$ 30-50/mês',
  ],
};
